FROM python:3.11.3-slim-bullseye

RUN apt-get update \
    && apt-get install -y cron

WORKDIR /usr/src/app

COPY ./requirements/api_requirements.txt .
RUN pip install --no-cache-dir -r api_requirements.txt

COPY ./api/entrypoint.sh .
RUN chmod +x entrypoint.sh

COPY ./api/src .

ENTRYPOINT ["/usr/src/app/entrypoint.sh"]