name: newman-tests

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Rename .env file
        run: mv ./.env.sample ./.env

      - name: Build
        run: docker-compose -f ./docker-compose.yml build

      - name: Up
        run: docker-compose -f ./docker-compose.yml up -d

      - name: Attach to Newman
        run: docker attach metallurg-moskva_parsing_newman_1
